### ISSUE TITLE
Assertion Error During MSA

### ISSUE THREAD

**Issue by zsilfen** [MasaakiU/MultiplexNanopore#3]
Hi Masaaki,

I am getting the following error when the MSA is executing. I've been getting this error both on Colab and locally.  

If I can provide any additional information let me know!

`executing MSA...
processing psb5-cmv-pe6d-bgh.fasta...
polishing reads #722...: 100%|█████████████████████████████| 129748/129748 [02:10<00:00, 993.66it/s]
Traceback (most recent call last):

  File ~/anaconda3/envs/sequencing/lib/python3.11/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Sequencing2.py:12
    savemoney.post_analysis('/Users/zacharysilfen/Desktop/Sequencing/sample_data/Group 2/', '/Users/zacharysilfen/Desktop/Sequencing/sample_data/Group 2/Results/')

  File ~/anaconda3/envs/sequencing/lib/python3.11/site-packages/savemoney/post_analysis/post_analysis.py:29 in post_analysis
    return post_analysis_separate_paths_input(plasmid_map_paths, fastq_paths, save_dir_base, **param_dict)

  File ~/anaconda3/envs/sequencing/lib/python3.11/site-packages/savemoney/post_analysis/post_analysis.py:52 in post_analysis_separate_paths_input
    my_msa_list = pac.execute_msa(result_dict, query_assignment, param_dict)

  File ~/anaconda3/envs/sequencing/lib/python3.11/site-packages/savemoney/post_analysis/post_analysis_core.py:201 in execute_msa
    my_msa_list.append(my_msa_aligner.execute(param_dict))

  File ~/anaconda3/envs/sequencing/lib/python3.11/site-packages/savemoney/modules/msa.py:646 in execute
    my_msa = my_msa.execute_soft_clipping()     ### time consuming ###

  File ~/anaconda3/envs/sequencing/lib/python3.11/site-packages/savemoney/modules/msa.py:1343 in execute_soft_clipping
    assert my_cigar_aligned[cur_idx] in "=XIS" # HO DN

AssertionError`

**Comment by MasaakiU** [comment]
Hello zsilfen, 
Thank you for the bug report.
Is it possible for you to share me the dataset (plasmid maps and fastq file) that causing you trouble?
If you compress your datasets into ZIP file, you can [attach files](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) up to 25MB with your comments.
If you do not want to upload your dataset on this thread, could you personally send it to me ([mu84@cornell.edu](mailto:mu84@cornell.edu))?
I will only use your data to fix the bug.

**Comment by zsilfen** [comment]
Of course!  Will send now

**Comment by MasaakiU** [comment]
I received, I'll try to fix the issue and let you know the updates as soon as possible.

**Comment by MasaakiU** [comment]
Hello zsilfen, 
The bug was fixed and Colab page and the package was updated (version 0.2.14).
I'll send results analyzed on my side by email later.
Sorry for the inconvenience.
