### ISSUE TITLE
KeyError during consensus calculation

### ISSUE THREAD

**Issue by astefek1** [MasaakiU/MultiplexNanopore#4]
Hi Dr. Uematsu,

I am repeatedly running into the following error in step 3_6 (calculate consensus) and hoping you may be able to help resolve the issue. I'd be happy to send any files needed. Thanks! 

-Adam Stefek

executing MSA...
processing pDG459_can2_pair2.dna...
polishing reads #95....: 100%|██████████████████████████████| 60408/60408 [00:24<00:00, 2423.96it/s]
generating consensus...: 100%|█████████████████████████████▉| 14260/14273 [00:03<00:00, 3760.78it/s]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-8-bb3b4057ce9d>](https://localhost:8080/#) in <cell line: 51>()
     49 
     50 # 4. MSA/consensus
---> 51 my_msa_list = pac.execute_msa(result_dict, query_assignment, param_dict)

**Comment by MasaakiU** [comment]
Hello Adam, 
Thank you for the bug report and sorry for the inconvenience.
Is it possible for you to share me the dataset (plasmid maps and fastq file) that causing you trouble?
If you compress your datasets into ZIP file, you can [attach files](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) up to 25MB with your comments.
If you do not want to upload your dataset on this thread, could you personally send it to me ([mu84@cornell.edu](mailto:mu84@cornell.edu))?
I will only use your data to fix the bug.

**Comment by astefek1** [comment]
Hi Masaaki, 

Thanks so much for your help. I sent you an email with the files I have been using.

**Comment by MasaakiU** [comment]
The bug was due to the alignment error when there is an insert at the end of the plasmid map.
It was fixed on 3/21/2024.
